### ISSUE TITLE
Negative value (-1)

### ISSUE THREAD

**Issue by Namelessinterester** [maxnowack/homebridge-dht-sensor#32]
Hello. When my dht22 showing out side temp lower then 0. So -1 in iOS I see No Response. Please help. Thanks!

**Comment by maxnowack** [comment]
It looks like iOS is expecting a value >=0
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L644

**Comment by Namelessinterester** [comment]
I got it running using homebridge-dht.
![3f7c4ae1677cfe54de1ba7663d0784e57c9361be69983cdee6 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/15656688/22824566/1cdddca6-ef91-11e6-9bf2-953150d58d9b.jpg)
