### ISSUE TITLE
bcm2835_init: Unable to open /dev/mem: Permission denied

### ISSUE THREAD

**Issue by HapCoderWei** [maxnowack/homebridge-dht-sensor#40]
Hi, I installed this plugins without error, but after running the homebridge and open the Home app on my iphone, it suddenly give a fault and crashed. Please help. Thanks!
--------Error info-----------
bcm2835_init: Unable to open /dev/mem: Permission denied
Segmentation fault

**Comment by maxnowack** [comment]
The user who run homebridge need permissions to access `/dev/mem`. Please make sure that the user has sufficient permissions

**Comment by HapCoderWei** [comment]
Hi, Sorry to trouble you again. I think it is caused by the permission. Could you tell me how to solve it?
I run homebridge on a raspberry pi, and as user pi. Thanks for any advices.  :)
