### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by daniel4099** [maxnowack/homebridge-dht-sensor#43]
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
npm ERR! Linux 4.4.50+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "homebridge-dht-sensor"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! node-dht-sensor@0.0.32 postinstall: `node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-dht-sensor@0.0.32 postinstall script 'node-gyp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-dht-sensor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-dht-sensor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-dht-sensor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-06-10T11_12_13_368Z-debug.log

**Comment by maxnowack** [comment]
What command did you use to install the plugin?

**Comment by xpyctum** [comment]
@maxnowack same problem. Used default command in readme.
```npm install homebridge-dht-sensor```

**Comment by maxnowack** [comment]
You're missing the `-g` argument. https://github.com/maxnowack/homebridge-dht-sensor#installation

**Comment by xpyctum** [comment]
Tired with -g flag. No changes.

**Comment by toshibochan** [comment]
Sudo npm install -g homebridge-dht-sensor

**Comment by toshibochan** [comment]
sudo npm install -g homebridge-dht-sensor

**Comment by xpyctum** [comment]
nothing changes. ¯\_(ツ)_/¯ 
![No](https://pp.userapi.com/c837622/v837622517/48ff4/mi6dRuUqQmU.jpg)
