### ISSUE TITLE
unable to install 

### ISSUE THREAD

**Issue by lowrisk75** [maxnowack/homebridge-dht-sensor#44]
I keep having the following issue.
I'm pretty sure BCM2835 is installed,
I'm using homebridge using docker 

USER: root
DIR: /homebridge
CMD: npm install --unsafe-perm --save homebridge-dht-sensor@latest

> node-dht-sensor@0.0.32 preinstall /homebridge/node_modules/node-dht-sensor
> ./check-lib.sh

+--------------------------------------------------------------------------------+
| ERROR: Library BCM2835 not found!                                              |
| Make sure you follow instructions from http://www.airspayce.com/mikem/bcm2835/ |
| to install the BCM2835 library on your system first then install this addon.   |
+--------------------------------------------------------------------------------+

> node-dht-sensor@0.0.32 install /homebridge/node_modules/node-dht-sensor
> node-gyp configure

> node-dht-sensor@0.0.32 postinstall /homebridge/node_modules/node-dht-sensor
> node-gyp build

make: Entering directory '/homebridge/node_modules/node-dht-sensor/build'
  CXX(target) Release/obj.target/node_dht_sensor/node-dht-sensor.o
../node-dht-sensor.cpp: In member function 'virtual void ReadWorker::HandleOKCallback()':
../node-dht-sensor.cpp:48:29: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
       callback->Call(3, argv);
                             ^
In file included from ../node-dht-sensor.cpp:2:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
  CXX(target) Release/obj.target/node_dht_sensor/dht-sensor.o
../dht-sensor.cpp:4:21: fatal error: bcm2835.h: No such file or directory
 #include <bcm2835.h>
                     ^
compilation terminated.
make: *** [node_dht_sensor.target.mk:96: Release/obj.target/node_dht_sensor/dht-sensor.o] Error 1
make: Leaving directory '/homebridge/node_modules/node-dht-sensor/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.30-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /homebridge/node_modules/node-dht-sensor
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-dht-sensor@0.0.32 postinstall: `node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-dht-sensor@0.0.32 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-11T17_19_46_794Z-debug.log

Command failed. Please review log for details

**Comment by maxnowack** [comment]
How does your Dockerfile look like? I also use homebridge with docker. You can take a look at my Dockerfile here: https://github.com/maxnowack/dockerfiles/blob/master/homebridge/Dockerfile

**Comment by lowrisk75** [comment]
ok I think I'm way to new using docker, my previous install of homebridge in the past was without docker, I don't know why I used docker this time but I'm a bit lost, that probably the main issue. I will have a closer look
